#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard: us
  timezone: America/New_York
  storage:
    config:
      - type: lvm
        pvs:
          - /dev/sda*  # Adjust if your disk is different
        vg: ubuntu-vg
        lv:
          - name: root
            size: 20%  # Adjust root partition size as needed
          - name: swap
            size: 16GB
  users:
    - name: your_username
      groups: sudo
      sudo: ALL=(ALL) NOPASSWD:ALL
      passwd: # Don'e enter RAW passwords here , instead use hashed values.
      shell: /bin/bash
      home: /home/your_username
  packages:
    - tasksel
    - ubuntu-desktop-minimal
    - build-essential
    - git
    - curl
    - wget
    - vim
    - htop
    - net-tools
    - openssh-server
    - flatpak
    - zram-config
    - amd64-microcode
    - vlc 
    - fswatch
  late-commands:
    - curtin in-target -- bash -c "echo 'deb http://archive.ubuntu.com/ubuntu oriocle main restricted universe multiverse' > /etc/apt/sources.list"
    - curtin in-target -- bash -c "echo 'deb http://archive.ubuntu.com/ubuntu oriocle-updates main restricted universe multiverse' >> /etc/apt/sources.list"
    - curtin in-target -- bash -c "echo 'deb http://archive.ubuntu.com/ubuntu oriocle-backports main restricted universe multiverse' >> /etc/apt/sources.list"
    - curtin in-target -- bash -c "echo 'deb http://security.ubuntu.com/ubuntu oriocle-security main restricted universe multiverse' >> /etc/apt/sources.list"
    - apt update
    - apt upgrade -y
    - apt autoremove -y
    # - apt install linux-image-generic-hwe-24.10 -y  # Install the stable HWE kernel
    # - apt install linux-headers-$(uname -r) dkms nvidia-driver-535 -y  # Adjust driver version if needed ## CAN Break the installation easy, use with caution.
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install flathub org.qbittorrent.qBittorrent -y
    - systemctl enable fstrim.timer  # Enable TRIM for SSDs
    - reboot