#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard: US
  timezone: Asia/Amman
  storage:
    config:
      - type: lvm
        pvs:
          - /dev/sda*  # Adjust if your disk is different
        vg: ubuntu-vg
        lv:
          - name: root
            size: 40%  # Adjust root partition size as needed
          - name: swap
            size: 8GB
  users:
    - name: madara
      groups: sudo
      sudo: ALL=(ALL) NOPASSWD:ALL
      passwd: # Don'e enter RAW passwords here, instead use hashed values.
      shell: /bin/bash
      home: /home/madara
  packages:
    - ubuntu-desktop-minimal
    - build-essential
    - git
    - curl
    - wget
    - vim
    - htop
    - net-tools
    - openssh-server
    - flatpak
    - zram-config
    - amd64-microcode
    - vlc  # Versatile media player
    - ffmpeg  # For command-line media operations
  late-commands:
    - curtin in-target -- bash -c "echo 'deb http://archive.ubuntu.com/ubuntu oriocle main restricted universe multiverse' > /etc/apt/sources.list"
    - curtin in-target -- bash -c "echo 'deb http://archive.ubuntu.com/ubuntu oriocle-updates main restricted universe multiverse' >> /etc/apt/sources.list"
    - curtin in-target -- bash -c "echo 'deb http://archive.ubuntu.com/ubuntu oriocle-backports main restricted universe multiverse' >> /etc/apt/sources.list"
    - curtin in-target -- bash -c "echo 'deb http://security.ubuntu.com/ubuntu oriocle-security main restricted universe multiverse' >> /etc/apt/sources.list"
    - apt update
    - apt upgrade -y
    - apt autoremove -y
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install flathub org.qbittorrent.qBittorrent -y
    - systemctl enable fstrim.timer  # Enable TRIM for SSDs
    - systemctl enable unattended-upgrades
    - reboot
